name: carcraft
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.0
  flutter_masked_text2: ^0.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^4.0.0

# flutter_launcher_icons:
#   android: false    # Установите true, если хотите иконки для Android
#   ios: true
#   image_path: "assets/icons/png/logo3.png"  # Путь к вашему файлу иконки

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/speedometr.svg
    - assets/images/speedometer.gif
    - assets/images/ezgif-3-362f31f48f.gif
    - assets/images/apped.svg
    - assets/apped.svg
    - assets/apped_new.svg
    - assets/apped_new2.svg

  fonts:
    - family: Microsoft
      fonts:
        - asset: assets/fonts/microsoftsansserif.ttf
          weight: 700
    - family: SF-Pro-Display
      fonts:
         - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Heavy.otf
           weight: 700