name: mobile
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  flutter_masked_text2: ^0.9.0
  lottie: ^3.1.0
  go_router: ^14.6.0
  logger: ^2.4.0
  shrink_sidemenu: ^2.0.0+2-null-safety
  circular_menu: ^4.0.0
  permission_handler: ^11.3.1
  icons_launcher: ^2.0.7
  provider: ^6.1.2
  postgres: ^2.4.0
  flutter_dotenv: ^5.2.1
  # postgres: ^3.4.7
  # flutter_native_splash: ^2.2.16


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^4.0.0

# flutter_launcher_icons:
#   android: false    # Установите true, если хотите иконки для Android
#   ios: true
#   image_path: "assets/icons/png/logo3.png"  # Путь к вашему файлу иконки

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/icons/gif/momentum_pay.gif
    - assets/icons/gif/vin_by_vin.gif
    - assets/icons/gif/notarial_control.gif
    - assets/icons/gif/monitoring.gif
    - assets/icons/gif/smart_control.gif
    - assets/icons/gif/remoney.gif
    # - assets/speedometr.svg
    - assets/images/speedometer.gif
    - assets/images/ezgif-3-362f31f48f.gif
    - assets/images/apped.svg
    - assets/apped.svg
    - assets/apped_new.svg
    - assets/apped_new2.svg
    - assets/json/animated_speed.json
    - assets/json/animat.json
    - assets/certs/RootCA.pem
    - assets/config/.env

  fonts:
    - family: Microsoft
      fonts:
        - asset: assets/fonts/microsoftsansserif.ttf
          weight: 700
    - family: SF-Pro-Display
      fonts:
         - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Heavy.otf
           weight: 700
icons_launcher:
  image_path: "assets/icons/carCraftLogo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

# flutter_native_splash:
#   # color: "#ffffff" # Цвет фона
#   color: "#c8cad4" # Цвет фона
#   image: assets/icons/carCraftLogo.png # Путь к изображению
#   fill: true
#   android: true
#   ios: true          